### ISSUE TITLE
not posting to youtube?

### ISSUE THREAD

**Issue by redshojin** [popcorn9499/Youtube-Discord-Relay-Bot#7] opened 2017-05-24 23:13 UTC
For some reason I get everything from youtube to discord, but nothing comes back to youtube to post into that chat. Any idea why? I'm thinking it might be the servername in the config maybe?

**Comment by popcorn9499** [comment] 2017-05-25 00:11
Ya I never got to implementing that. I will look into it more when I get time. Life got in the way. I should possibly look into it again shortly. Sorry about that

**Comment by popcorn9499** [comment] 2017-05-25 00:13
That would be a problem with the coding on my end. I never learned that part of the api. Well never successfully learned it anyways. It was something due to when i get the access key portion i didnt get read write access i only got read so it wouldn't let me add messages.

**Comment by popcorn9499** [comment] 2017-05-25 00:16
#1 Duplicate of that issue there.

**Comment by popcorn9499** [comment] 2017-05-25 00:17
I'm going to close the issue as i had one there from the beginning.

**Closed as completed by popcorn9499** 2017-05-25 00:17 UTC
Labels: bug, enhancement, help wanted
